# Generated by Django 5.2.5 on 2025-08-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_task_created_by_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
